config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :blogs, only: [:show], path: 'blogs' do
    resources :posts, except: [:index], path: 'posts'
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user

  has_many :posts

  validates :title, :slug, presence: true
  validates :slug, uniqueness: true

  def to_param
    slug
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :blog

  validates :title, :content, presence: true

  def modified?
    created_at != updated_at
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :blog
  has_many :posts, through: :blog

  accepts_nested_attributes_for :blog

  validates :time_zone, inclusion: ActiveSupport::TimeZone.all.map(&:name)
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from TinyBlog::AccessDenied do |_|
    message = 'You are not authorized to view that page.'
    respond_to do |format|
      format.json do
        render json: { error: message, status: :forbidden }
      end
      format.all { redirect_to root_path, alert: message }
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def show
    @posts = @blog.posts.decorate

    respond_to do |format|
      format.html
      format.json { render json: @blog }
    end
  end

  private

  def set_blog
    @blog = Blog.find_by(slug: params[:id]).decorate
  end

  def blog_params
    params.require(:blog).permit(:title, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @blogs = Blog.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PostsHelper

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  before_action :current_user_can_modify_post, except: [:new, :create, :show]
  before_action :set_blog, except: [:show]

  def show
    @blog = @post.blog

    respond_to do |format|
      format.html
      format.json { render json: @post }
    end
  end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = Post.new(post_params)
    @post.blog = @blog

    respond_to do |format|
      if @post.save
        format.html do
          redirect_to blog_post_path(@blog, @post), notice: 'Post was successfully created.'
        end
        format.json { render json: @post, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html do
          redirect_to blog_post_path(@blog, @post), notice: 'Post was successfully updated.'
        end
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to blog_path(@blog) }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id]).decorate
  end

  def set_blog
    @blog = current_user.blog
  end

  def current_user_can_modify_post
    unless post_belongs_to_user @post
      raise TinyBlog::AccessDenied
    end
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    prepend_before_action :configure_sign_up_params, only: [:create]
    prepend_before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    def new
      super do |resource|
        resource.build_blog
      end
    end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up) do |u|
        u.permit(
          :email,
          :password,
          :password_confirmation,
          :first_name,
          :last_name,
          :time_zone,
          blog_attributes: [:title, :slug]
        )
      end
    end

    # If you have extra params to permit, append them to the sanitizer.
    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update) do |u|
        u.permit(
          :email,
          :password,
          :password_confirmation,
          :current_password,
          :first_name,
          :last_name,
          :time_zone,
          blog_attributes: [:id, :title, :slug]
        )
      end
      # devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date_time(object)
    object.strftime('%F @ %r %Z')
  end

  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' unless devise_error_messages?

    messages = resource
               .errors
               .full_messages
               .map { |msg| content_tag(:li, msg) }
               .join
    sentence = I18n.t(
      'errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase
    )

    html = <<-HTML
    <div class="panel panel-danger">
      <div class="panel-heading">
        #{sentence}
      </div>
      <div class="panel-body">
        <ul>#{messages}</ul>
      </div>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_belongs_to_user(post)
    return false unless current_user.present?

    post.blog.user_id == current_user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/show.html.slim
- title @blog.title

h2= @blog.title
h3
  |By&nbsp;
  = @blog.author_information

- @posts.each do |post|
  .row
    .col-md-4
      = link_to post.title, blog_post_path(@blog, post)
    .col-md-4
      = post.created_at_in_user_timezone
    - if post_belongs_to_user post
      .col-md-4
        ul.list-inline
          li= link_to 'Edit', edit_blog_post_path(@blog, post), class: 'btn btn-default btn-sm'
          li= link_to 'Delete', blog_post_path(@blog, post), data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger btn-sm'

- if @blog.posts.empty?
  p No posts

app/views/home/index.html.slim
h2 Tiny Blog

h3 Check out blogs below

- @blogs.each do |blog|
  h3= link_to blog.title, blog_path(blog)

- if @blogs.empty?
  h3 No blogs found

app/views/layouts/application.html.slim
doctype html
html
  head
    meta(charset="utf-8")
    meta(http-equiv="X-UA-Compatible" content="IE=edge")
    meta(name="viewport" content="width=device-width, initial-scale=1")
    title
      = content_for(:title) || 'Tiny Blog'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    nav.navbar.navbar-inverse.navbar-fixed-top(role="navigation")
      .container
        .navbar-header
          button.navbar-toggle.collapsed(type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar")
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'Tiny Blog', root_url, class: 'navbar-brand'
        #navbar.collapse.navbar-collapse
          ul.nav.navbar-nav
            li= link_to 'Home', root_path
            - if user_signed_in?
              li
                = link_to 'Create post', new_blog_post_path(current_user.blog)
              li
                = link_to 'Edit user profile', edit_user_registration_path
              li
                = link_to 'Logout', destroy_user_session_path, method: :delete
            - else
              li
                = link_to 'Sign up as User', new_user_registration_path
              li
                = link_to 'Sign in as User', new_user_session_path
    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          button.close(type="button" data-dismiss="alert")
            span(aria-hidden="true")
              | ×
            span.sr-only
              | Close
          = msg
      = yield

app/views/posts/_form.html.slim
= form_for([@blog, @post]) do |f|
  - if @post.errors.any?
    .panel.panel-danger
      .panel-heading
        = pluralize(@post.errors.count, "error")
        |&nbsp;
        |prohibited this post from being saved

      .panel-body
        ul
          - @post.errors.full_messages.each do |message|
            li= message

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control', rows: '10'
    p.help-block
      |Enter content in&nbsp;
      = link_to 'markdown', 'https://daringfireball.net/projects/markdown/syntax'
  = f.submit 'Submit', class: 'btn btn-primary'

app/views/posts/edit.html.slim
- title 'Editing Post'

h2 Editing Post

= render 'form'

app/views/posts/new.html.slim
- title 'New Post'

h2 New Post

= render 'form'

app/views/posts/show.html.slim
- title @post.title

- if post_belongs_to_user @post
  = link_to 'Edit', edit_blog_post_path(@blog, @post), class: 'btn btn-default'

h1= @post.title

p
  |Created on:&nbsp;
  = @post.created_at_in_user_timezone
- if @post.modified?
  p
    |Last Updated:&nbsp;
    = @post.updated_at_in_user_timezone

= @post.content_html